### ISSUE TITLE
Don't have appropriate error code

### ISSUE THREAD

**Issue by Jun69** [vesoft-inc/nebula-go#119]
when session expired ,service return code -5. but in this link [https://github.com/vesoft-inc/nebula-go/blob/master/nebula/ttypes.go](https://github.com/vesoft-inc/nebula-go/blob/master/nebula/ttypes.go)   ErrorCode_E_SESSION_INVALID ErrorCode = -1002

**Comment by wey-gu** [comment]
Thank you @Jun69! @laura-ding we are working on unifying client/server Error Code right?

**Comment by Sophie-Xie** [comment]
https://github.com/vesoft-inc/nebula/issues/3092

**Comment by Sophie-Xie** [comment]
Will be fixed in the future.
