### ISSUE TITLE
Compatible adaptation govendor

### ISSUE THREAD

**Issue by sallelujah** [vesoft-inc/nebula-go#123]
Although i'm updateted go version to 1.55.11, but still using go vendor, i'm getting error when run my code local as follow:
`cannot find package "github.com/vesoft-inc/nebula-go/v2" in any of:
	/Users/xxx/go/src/gitlab.xxx.com/xxx/my-proj/vendor/github.com/vesoft-inc/nebula-go/v2 (vendor tree)
	/usr/local/Cellar/go/go1.15.11/src/github.com/vesoft-inc/nebula-go/v2 (from $GOROOT)
	/Users/xxx/go/src/github.com/vesoft-inc/nebula-go/v2 (from $GOPATH)`

so, i'm still want to use govendor to manage my go repo
but how can i do to avoid this error when using v2.0.0-ga branch ?

thx

**Comment by wey-gu** [comment]
Could you help take a look at sallelujah's issue? @Aiee @jievince Thanks :)

**Comment by sallelujah** [comment]
![image](https://user-images.githubusercontent.com/13994643/129359610-781469a7-e8f7-46ce-8afd-44b8bcf100bf.png)

**Comment by sallelujah** [comment]
> Could you help take a look at sallelujah's issue? @Aiee @jievince Thanks :)

got error just like this when i'm using golang version1.15.11, with GOPATH  and govendor mode
![image](https://user-images.githubusercontent.com/13994643/129359680-db0ca3a9-3a3c-4e0b-813b-0cfd3b46ac5a.png)

**Comment by sallelujah** [comment]
uh, may be  i had  found the command:
govendor fetch github.com/vesoft-inc/nebula-go@v2.0.0-ga

**Comment by Aiee** [comment]
> uh, may be i had found the command:
> `govendor fetch github.com/vesoft-inc/nebula-go@v2.0.0-ga`

Good job for the solution! 
Though I want to mention that the go vendor's [official repo](https://github.com/kardianos/govendor) has been archived, and the author has suggested using `go mod` instead.
