### ISSUE TITLE
would you please add more samples for parse resultSet?

### ISSUE THREAD

**Issue by Reid00** [vesoft-inc/nebula-go#124]
I only find two samples in basic_example/goroutine_example and there is barely parse resultSet demo？ is this possible to provide parse method for result or add more cases?

**Comment by wey-gu** [comment]
Thank you @Reid00!
@Aiee could we add examples on resultSet parsing?

**Comment by Aiee** [comment]
Hi, you may refer to https://github.com/vesoft-inc/nebula-go/blob/e579867d0a2ff3c5240066f868d5d0e20df02d61/result_set_test.go#L515
for more cases.

**Comment by Aiee** [comment]
Feel free to reopen/ask in the forum if you have further questions.
