### ISSUE TITLE
Add fetch/Go.Lookup query example

### ISSUE THREAD

**Issue by ansarizafar** [vesoft-inc/nebula-go#15]
Please add fetch/Go.Lookup query example to read me or documentation.

**Comment by vnnw** [comment]
Any update?

**Comment by Aiee** [comment]
Like the example stated, after you get a session, use the `execute()` method to execute a query:
```
queryStr := ""
// Excute a query
resultSet, err := session.Execute(queryStr)
if err != nil {
	fmt.Print(err.Error())
	return
}
```
