### ISSUE TITLE
storageClient read api to be wrapped

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-go#161]
as title, we are missing this, could we consider implementing go-sclient?

**Comment by wey-gu** [comment]
-  https://discuss.nebula-graph.com.cn/t/topic/6663/8?u=wey

**Comment by Aiee** [comment]
We are actually removing python storage client in v3.0.0 release since this is rarely used, also the meta/storage clients are not safe because they don't authenticate the user.
