### ISSUE TITLE
Can we load the result to struct?

### ISSUE THREAD

**Issue by akhilravuri1** [vesoft-inc/nebula-go#189]
Hi,

I am using golang 17 and nebula-go 2.5.1 versions

In other go-clients when we query data we can load that into a struct.

```
result, err := client.Execute(query)
result.Scan(&struct)
```

But here I can see the data is returned as string type.

```
	// Get a row from resultSet
	record, err := resultSet.GetRowValuesByIndex(0)
	if err != nil {
		log.Error(err.Error())
	}

	// Print whole row
	fmt.Println("The first row elements: \n", record.String())
```

If there is a way please document it or point me to that documentation link.

Thanks,
Akhil

**Comment by wey-gu** [comment]
Thanks Akhil and welcome to the nebula community :)
@Aiee , could you please help with Akhil?

**Comment by Aiee** [comment]
Hello @akhilravuri1, you may update both the client and Nebula service to v2.6.0 or later to use the `ExecuteJson()` interface which returns the query result as a json string, and then you could use https://github.com/vesoft-inc/nebula-go/blob/master/json_example/parse_json_example.go as a reference to save the result in a self-defined struct.
