### ISSUE TITLE
偶尔报错：fail to authenticate, error: Insert userIpSessionCount to local cache failed

### ISSUE THREAD

**Issue by KenshinZZZZ** [vesoft-inc/nebula-go#220]
用的v3.0.0版本，找不到原因

**Comment by HarrisChu** [comment]
need more info

**Comment by QingZ11** [comment]
@KenshinZZZZ hi, I have noticed that the issue you created hasn’t been updated for nearly a month, is this issue been resolved? If not resolved, can you provide some more information? If solved, can you close this issue?

Thanks a lot for your contribution anyway 😊

**Comment by QingZ11** [comment]
@zhangxinghb 你需要提供多点信息。这个报错信息是如何发生的？你做了什么操作？

**Comment by QingZ11** [comment]
这个 issue 超过一个月没有更新内容了，这边先行关闭了。如果你有任何更新的内容，可以再打开这个 issue 哈。

谢谢你的反馈 😊
