### ISSUE TITLE
how to check a connection is closed 

### ISSUE THREAD

**Issue by son2408** [vesoft-inc/nebula-go#233]
![image](https://user-images.githubusercontent.com/32300653/200175764-596d9017-1ce0-4986-b9dc-51473bc9a41d.png)
![image](https://user-images.githubusercontent.com/32300653/200175926-ddb695c0-91d2-437a-9d73-918e1b2a5bd6.png)
I can't acess field closed of nebula.ConnectionPoo, but it exists

**Comment by son2408** [comment]
> ![image](https://user-images.githubusercontent.com/32300653/200175764-596d9017-1ce0-4986-b9dc-51473bc9a41d.png) ![image](https://user-images.githubusercontent.com/32300653/200175926-ddb695c0-91d2-437a-9d73-918e1b2a5bd6.png) I can't acess field closed of nebula.ConnectionPool, but it exists

**Comment by wey-gu** [comment]
cc @Aiee

**Comment by QingZ11** [comment]
Hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊

这个 issue 超过一个月没有更新内容了，这边先行关闭了。如果你有任何更新的内容，可以再打开这个 issue 哈。
