### ISSUE TITLE
What is the meaning of adding .editorconfig file to the project?

### ISSUE THREAD

**Issue by monkey92t** [vesoft-inc/nebula-go#262]
It from #3, i don't understand why this file exists..

**Comment by yixinglu** [comment]
you could refer [the document](https://editorconfig.org/) and get to know what's the editorconfig.

**Comment by monkey92t** [comment]
> you could refer [the document](https://editorconfig.org/) and get to know what's the editorconfig.

Oh~, I understand the role of the editorconfig file, what I want to ask is why use editorconfig to configure the go project.

It forces everyone to use the configuration in editorconfig. For go projects, we should abide by the specifications of gofmt/golangci-lint. 

We only need to ensure that the submitted code conforms to the specifications, rather than setting the IDE tools used by users.

It forced to change my goland configuration, I think the editorconfig file is configured for everyone's habits, not for the project.

**Comment by yixinglu** [comment]
editorconfig is not only for configuring local editing, but also for configuring the display of code in GitHub, such as tabbing indented by 2 spaces

**Comment by QingZ11** [comment]
Hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊

这个 issue 超过一个月没有更新内容了，这边先行关闭了。如果你有任何更新的内容，可以再打开这个 issue 哈。
