### ISSUE TITLE
v3.4.1 session 泄露

### ISSUE THREAD

**Issue by zjtaozjtw** [vesoft-inc/nebula-go#268]
当session过期后，在ExecuteWithParameter方法中，重试获取的session没有用来更新getIdleSession()方法获取的session，导致后面在调用returnSession()方法时，放回idleSession里面的还是那个过期的session，于是每次就会不断重试来创建新的session，导致session不断上涨。

**Comment by wey-gu** [comment]
@Aiee could you please kindly take a look at this issue?

**Comment by HarrisChu** [comment]
could we close this issue?

**Comment by Aiee** [comment]
Closed by https://github.com/vesoft-inc/nebula-go/pull/269
