### ISSUE TITLE
`Space was not chosen` when connecting to LB in cloud with HTTP2

### ISSUE THREAD

**Issue by wenhaocs** [vesoft-inc/nebula-go#287]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**
When using HTTP/2 mode, there will be small % of requests failing due to error "query failed with error code -1009 and error message SemanticError: Space was not chosen." 

![Image](https://github.com/vesoft-inc/nebula-go/assets/19355821/52c1ff42-4da7-42f7-9fcc-a1a9cc50857f)

**Your Environments (__required__)**
AWS with LB

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by wenhaocs** [comment]
Based on experiment from @HarrisChu 
This is because the LB has multiple connections to the server side. For every session we create at client side, we will call `use space`. However, if the LB has more connections than the number of sessions, it is possible some connections is not associated with the session calling `use graph`. On the other hand, HTTP server is usually stateless. On request, it may or may not reuse the previous connection with which `use space` was executed.

**Comment by HarrisChu** [comment]
![image](https://github.com/vesoft-inc/nebula-go/assets/1726587/1bbee93d-0a99-46f2-87e2-dde172d19129)
![image](https://github.com/vesoft-inc/nebula-go/assets/1726587/f7795849-9998-47bd-bd9d-d49cc739f84f)

client -> :8080 -> :9119 and :9449

when 
1. create session and use space with connection to :9119
2. session space info is not sync to meta.
3. and then execute statement with connection to :9449

and then it would cause `Space was not chosen` error.

**Comment by wenhaocs** [comment]
和Snap确认了，使用Envoy后，同一个client的不同Http stream，可能会hit到不同的graphd。所以每次创建新的session后，需要立马写入meta。

**Comment by HarrisChu** [comment]
refer https://github.com/vesoft-inc/nebula/pull/2833/

**Comment by xiajingchun** [comment]
确定要通过修改内核来实现，即在每次创建session，use space直接上报给meta，是否通过flag还是只做在snap分支由研发来决定。这个方案也会有些不足的地方，比如1）每次session claim的时候graphd会上报更多的信息给到meta；2）session idle timeout带来的重试问题等。
另外，sticky session的方式即使snap的LB支持，我们会需要修改fbthrift http2的实现来支持cookie，另外这个方案在HPA下也会有问题，不能完全满足需求。

**Comment by Sophie-Xie** [comment]
> 确定要通过修改内核来实现，即在每次创建session，use space直接上报给meta，是否通过flag还是只做在sc分支由研发来决定。这个方案也会有些不足的地方，比如1）每次session claim的时候graphd会上报更多的信息给到meta；2）session idle timeout带来的重试问题等。 另外，sticky session的方式即使sc的LB支持，我们会需要修改fbthrift http2的实现来支持cookie，另外这个方案在HPA下也会有问题，不能完全满足需求。
