### ISSUE TITLE
What if user wants to pass in a `int64` as param?

### ISSUE THREAD

**Issue by wenhaocs** [vesoft-inc/nebula-go#288]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

Take a look at here: https://github.com/vesoft-inc/nebula-go/blob/master/session.go#L281

**Your Environments (__required__)**

* OS: `uname -a`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by nyadav-sc** [comment]
Seeing this error when trying to pass int64 

`failed to parse params: Only support convert boolean/float/int/string/map/list to nebula.Value but int64"`

**Comment by syedzubeen** [comment]
Hey hi!
Can I work on this?

**Comment by wey-gu** [comment]
implemented via #348
