### ISSUE TITLE
Client API design, two sources for error

### ISSUE THREAD

**Issue by swdee** [vesoft-inc/nebula-go#37]
The design of this client library seems unusual to me as querying requires checking two sources for error instead of an expected single source.

The documentation checks `err` from client.Execute() as well as `nebula.IsError(resp)` such as in the following code from the readme.

```
  resp, err := client.Execute("SHOW HOSTS;")
  if err != nil {
    log.Fatal(err)
  }

  if nebula.IsError(resp) {
    log.Printf("ErrorCode: %v, ErrorMsg: %s", resp.GetErrorCode(), resp.GetErrorMsg())
  }
```

Why are two sources of error checking done and not one?

My expectation would be a single check such as;

```
resp, err := client.Execute("SHOW HOSTS;")

if err != nil {
    log.Printf("ErrorCode: %v, ErrorMsg: %s", resp.GetErrorCode(), resp.GetErrorMsg())
}
```

**Comment by Aiee** [comment]
Thank you for your feedback.
We have updated the error handling, as the detailed design-relative changes are explained in https://github.com/vesoft-inc/nebula-go/issues/40

Please feel free to open new issues, feedbacks/suggestions are always welcome.
