### ISSUE TITLE
[Bug] connect success when use invalid username/password

### ISSUE THREAD

**Issue by ustcr7** [vesoft-inc/nebula-go#6]
#### Issue description
client.go::Connect function do not check the error code of AuthResponse, and use invalid sessionId for subsequent query.

#### Steps to reproduce the issue
1.  client.Connect("user_not_exist", "password") 
2. client.Execute("SHOW HOSTS;")

#### What's the expected result?
report connect failed error (Bad username/password)

#### What's the actual result?
![image](https://user-images.githubusercontent.com/5212409/66381005-15923300-e9eb-11e9-94a5-c59610f6e473.png)

**Comment by monadbobo** [comment]
This was a bug, I have fixed it, you can try again.

Thanks.
