### ISSUE TITLE
go mod 无法下载最新版client

### ISSUE THREAD

**Issue by dollarkillerx** [vesoft-inc/nebula-go#77]
go version go1.13.5 linux/amd64

go.mod:
```
go 1.13

require (
	github.com/vesoft-inc/nebula-go v2.0.0-ga
)
```

Error:

require github.com/vesoft-inc/nebula-go: version "v2.0.0-ga" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2

**Comment by Aiee** [comment]
In the root directory of your project, ```$ go get -u -v github.com/vesoft-inc/nebula-go@master``` and you should be able to see that go.mod has been updated.

**Comment by conderls** [comment]
failed to get v2.0.0 with go v1.4 as well:
```bash
$ go version
go version go1.14 darwin/amd64

$ go get -u -v github.com/vesoft-inc/nebula-go@master
go: github.com/vesoft-inc/nebula-go master => v1.1.1-0.20210416024212-052593cefbb9
```

**Comment by Aiee** [comment]
> failed to get v2.0.0 with go v1.4 as well:
> 
> ```shell
> $ go version
> go version go1.14 darwin/amd64
> 
> $ go get -u -v github.com/vesoft-inc/nebula-go@master
> go: github.com/vesoft-inc/nebula-go master => v1.1.1-0.20210416024212-052593cefbb9
> ```

`go: github.com/vesoft-inc/nebula-go master => v1.1.1-0.20210416024212-052593cefbb9` This states that nebula-go has been updated.

**Comment by conderls** [comment]
> > failed to get v2.0.0 with go v1.4 as well:
> > ```shell
> > $ go version
> > go version go1.14 darwin/amd64
> > 
> > $ go get -u -v github.com/vesoft-inc/nebula-go@master
> > go: github.com/vesoft-inc/nebula-go master => v1.1.1-0.20210416024212-052593cefbb9
> > ```
> 
> `go: github.com/vesoft-inc/nebula-go master => v1.1.1-0.20210416024212-052593cefbb9` This states that nebula-go has been updated.

yes, but it is supposed to be v2.0.0, right? Otherwise, how can we get the v2.0+ version of nebula?

**Comment by Aiee** [comment]
> > > failed to get v2.0.0 with go v1.4 as well:
> > > ```shell
> > > $ go version
> > > go version go1.14 darwin/amd64
> > > 
> > > $ go get -u -v github.com/vesoft-inc/nebula-go@master
> > > go: github.com/vesoft-inc/nebula-go master => v1.1.1-0.20210416024212-052593cefbb9
> > > ```
> > 
> > 
> > `go: github.com/vesoft-inc/nebula-go master => v1.1.1-0.20210416024212-052593cefbb9` This states that nebula-go has been updated.
> 
> yes, but it is supposed to be v2.0.0, right? Otherwise, how can we get the v2.0+ version of nebula?

The Nebula-go version is only relative to the Github branch, which means if you run `$ go get -u -v github.com/vesoft-inc/nebula-go@master`, you will get the latest dependency. 
The ` v1.1.1-0.20210416024212-052593cefbb9` you see is an auto-generated version tag by Github. I will add this explanation to the README to clarify.

**Comment by everywan** [comment]
may be shold see this? https://github.com/vesoft-inc/nebula-go/issues/80
