### ISSUE TITLE
go mod 或许需要打版本

### ISSUE THREAD

**Issue by everywan** [vesoft-inc/nebula-go#80]
go get 2.0 时, 报错.

**命令以及报错详情**
```Bash
$ go get -v github.com/vesoft-inc/nebula-go@v2.0.0-ga
go get github.com/vesoft-inc/nebula-go@v2.0.0-ga: github.com/vesoft-inc/nebula-go@v2.0.0-ga: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

查阅文档可知, go 官方推荐在 v2 及更高版本中, 使用 `{path}/v2` 的方式, 从而管理多个版本. 参考文档: [Go Modules: v2 and Beyond](https://blog.golang.org/v2-go-modules)

**如何解决**
1. 在v2.x.x分支中, 更新 go.mod 为 `module github.com/vesoft-inc/nebula-go/v2`.
2. 在 master/relase2.x 分支中, 也进行如上更新

**如何复现**
1. 去掉goproxy: `unset GOPROXY`
2. 执行 go get `go get -v github.com/vesoft-inc/nebula-go@v2.0.0-ga`

**其他仓库的参考示例**
1. [iris v12.x.x 版本的go.mod](https://github.com/kataras/iris/blob/v12.1.6/go.mod)

**Comment by wey-gu** [comment]
Could you try this first for not blocking your work? 

`commit e37085b865d667a83109da24879b418d7ce4088a (tag: v2.0.0-ga)`

```bash
$ go get -v github.com/vesoft-inc/nebula-go@e37085b865d667a
go: downloading github.com/vesoft-inc/nebula-go v1.1.1-0.20210322063004-e37085b865d6
go: downloading github.com/facebook/fbthrift v0.0.0-20190922225929-2f9839604e25
github.com/facebook/fbthrift/thrift/lib/go/thrift
github.com/vesoft-inc/nebula-go/nebula
github.com/vesoft-inc/nebula-go/nebula/graph
github.com/vesoft-inc/nebula-go
```

**Comment by everywan** [comment]
> Could you try this first for not blocking your work?
> 
> `commit e37085b865d667a83109da24879b418d7ce4088a (tag: v2.0.0-ga)`
> 
> ```shell
> $ go get -v github.com/vesoft-inc/nebula-go@e37085b865d667a
> go: downloading github.com/vesoft-inc/nebula-go v1.1.1-0.20210322063004-e37085b865d6
> go: downloading github.com/facebook/fbthrift v0.0.0-20190922225929-2f9839604e25
> github.com/facebook/fbthrift/thrift/lib/go/thrift
> github.com/vesoft-inc/nebula-go/nebula
> github.com/vesoft-inc/nebula-go/nebula/graph
> github.com/vesoft-inc/nebula-go
> ```

Now I just test on 2.0, so it won't blocking my work.

**Comment by Aiee** [comment]
> go get 2.0 时, 报错.
> 
> **命令以及报错详情**
> 
> ```shell
> $ go get -v github.com/vesoft-inc/nebula-go@v2.0.0-ga
> go get github.com/vesoft-inc/nebula-go@v2.0.0-ga: github.com/vesoft-inc/nebula-go@v2.0.0-ga: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
> ```
> 
> 查阅文档可知, go 官方推荐在 v2 及更高版本中, 使用 `{path}/v2` 的方式, 从而管理多个版本. 参考文档: [Go Modules: v2 and Beyond](https://blog.golang.org/v2-go-modules)
> 
> **如何解决**
> 
> 1. 在v2.x.x分支中, 更新 go.mod 为 `module github.com/vesoft-inc/nebula-go/v2`.
> 2. 在 master/relase2.x 分支中, 也进行如上更新
> 
> **如何复现**
> 
> 1. 去掉goproxy: `unset GOPROXY`
> 2. 执行 go get `go get -v github.com/vesoft-inc/nebula-go@v2.0.0-ga`
> 
> **其他仓库的参考示例**
> 
> 1. [iris v12.x.x 版本的go.mod](https://github.com/kataras/iris/blob/v12.1.6/go.mod)

Hello everywan,
Thank you for your insightful suggestion. This is a part of our plan to accommodate the official Golang module guideline. 
Currently, you may specify the nebula-go version by  by substituting `<branch> `in `$ go get -u -v github.com/vesoft-inc/nebula-go@<branch>`.

**Comment by everywan** [comment]
> > go get 2.0 时, 报错.
> > **命令以及报错详情**
> > ```shell
> > $ go get -v github.com/vesoft-inc/nebula-go@v2.0.0-ga
> > go get github.com/vesoft-inc/nebula-go@v2.0.0-ga: github.com/vesoft-inc/nebula-go@v2.0.0-ga: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
> > ```
> > 
> > 
> > 查阅文档可知, go 官方推荐在 v2 及更高版本中, 使用 `{path}/v2` 的方式, 从而管理多个版本. 参考文档: [Go Modules: v2 and Beyond](https://blog.golang.org/v2-go-modules)
> > **如何解决**
> > 
> > 1. 在v2.x.x分支中, 更新 go.mod 为 `module github.com/vesoft-inc/nebula-go/v2`.
> > 2. 在 master/relase2.x 分支中, 也进行如上更新
> > 
> > **如何复现**
> > 
> > 1. 去掉goproxy: `unset GOPROXY`
> > 2. 执行 go get `go get -v github.com/vesoft-inc/nebula-go@v2.0.0-ga`
> > 
> > **其他仓库的参考示例**
> > 
> > 1. [iris v12.x.x 版本的go.mod](https://github.com/kataras/iris/blob/v12.1.6/go.mod)
> 
> Hello everywan,
> Thank you for your insightful suggestion. This is a part of our plan to accommodate the official Golang module guideline.
> Currently, you may specify the nebula-go version by by substituting `<branch> `in `$ go get -u -v github.com/vesoft-inc/nebula-go@<branch>`.

Ok. looking forward to that

**Comment by everywan** [comment]
exec `go get github.com/vesoft-inc/nebula-go/v2@v2.0.0-ga` succeed.
🎉
